### ISSUE TITLE
script exit after dest filesystem creation

### ISSUE THREAD

**Issue by xrmx** [RevolutionPi/imagebakery#1]
With this command:

```
./imagebakery/shrink_image.sh 2017-04-10-raspbian-jessie.img `date +%F`-raspbian-shrunk.img
```

The script exists after creating the destination filesystem 

```
The partition table has been altered.
Syncing disks.
+ partx 2017-05-30-raspbian-shrunk.img
NR START     END SECTORS SIZE NAME UUID
 1  8192   92159   83968  41M      402e4a57-01
 2 92160 7589887 7497728 3,6G      402e4a57-02
+ losetup /dev/loop1 2017-05-30-raspbian-shrunk.img
+ partprobe /dev/loop1
+ mkfs.ext4 /dev/loop1p2
mke2fs 1.43.4 (31-Jan-2017)
/dev/loop1p2 contains am ext4 file system
	last mounted on Tue May 30 10:14:04 2017
Proceed anyway? (y,N) y
```

Is it mke2fs returning something else than 0?

**Comment by xrmx** [comment]
If i type the very next two commands it fails mounting the file system:

```
[2999886.903080] EXT4-fs (loop1p2): bad geometry: block count 1034624 exceeds size of device (937216 blocks)
```

**Comment by xrmx** [comment]
After switching to raspbian lite image I've added a "|| /bin/true" after mkfs.ext4 call and got:
```
+ mkfs.ext4 /dev/loop1p2
mke2fs 1.43.4 (31-Jan-2017)
/dev/loop1p2 contiene un file system ext4
	last mounted on /tmp/src.23911 on Tue May 30 11:33:05 2017
Proceed anyway? (y,N) y

+ /bin/true
+ mkdir /tmp/dest.24594
+ mount /dev/loop1p2 /tmp/dest.24594
mount: wrong fs type, bad option, bad superblock on /dev/loop1p2,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
```

And dmesg | tail

```
[3003301.605438] JBD2: no valid journal superblock found
[3003301.605441] EXT4-fs (loop1p2): error loading journal
```

**Comment by l1k** [comment]
Hi @xrmx, thanks for your interest in Revolution Pi.

The `shrink_image.sh` script was only ever tested with the "non-lite" Raspbian image. One significant difference between lite and non-lite is the size of the FAT partition: 41M in the lite image, 63M in the non-lite image. The script copies the FAT partition verbatim into the new image but the size is hardcoded. Thus, if you invoke the script on a lite image, you copy the beginning of the ext4 partition to the new image and this causes mkfs.ext4 to issue a warning.

Of course, if the FAT partition is smaller, the ext4 partition will be a bit bigger, thus all the hardcoded sizes are incorrect as well.

The stock lite image has 334 MByte free. This might be sufficient to just skip the `shrink_image.sh` step and run `customize_image.sh` directly. If it is not sufficient, you'll need to *grow* the image rather than shrink it. Basically a combination of dd (seek to the end of the image file and add sparse space up to 3909091328 bytes) and resize2fs should do the trick.

Hope that helps!

**Comment by xrmx** [comment]
@l1k thanks for your answer, i've looked into the lite image after the normal one failing (https://github.com/RevolutionPi/imagebakery/issues/1#issuecomment-304811911). Thakns for the hint about the partition size!
I have a revolution pi core with the wheezy filesystem and i'd like to have an updated image based on jessie but am failing trying to build one.

**Comment by l1k** [comment]
@xrmx: Hm, the first comment seems to pertain to the lite image (recognizable by the 41M FAT partition). Does it fail for the non-lite image as well? If so, could you post the full script output?

It works for me with a non-lite image. However I have an older mkfs.ext4 version installed (1.42.12, 29-Aug-2014), not sure if that's relevant.

**Comment by xrmx** [comment]
@l1k i'm poking at customize_image ATM, will try to give it a run to shrink again later today.

**Comment by xrmx** [comment]
With master and `|| /bin/true` added after mkfs.ext4 i get this:
```
$ sudo ./shrink_image.sh 2017-04-10-raspbian-jessie.img `date +%F`-raspbian-shrunk.img
+ losetup -f
+ SRC_LOOP_DEV=/dev/loop1
+ losetup /dev/loop1 2017-04-10-raspbian-jessie.img
+ partprobe /dev/loop1
+ mkdir /tmp/src.28390
+ mount /dev/loop1p2 /tmp/src.28390
+ set +x
+ dd if=/dev/zero of=2017-05-30-raspbian-shrunk.img conv=sparse count=7634944
7634944+0 record dentro
7634944+0 record fuori
3909091328 bytes (3,9 GB, 3,6 GiB) copied, 1,97029 s, 2,0 GB/s
+ dd if=2017-04-10-raspbian-jessie.img of=2017-05-30-raspbian-shrunk.img conv=notrunc count=137215
137215+0 record dentro
137215+0 record fuori
70254080 bytes (70 MB, 67 MiB) copied, 0,126044 s, 557 MB/s
+ sfdisk --dump+ sed -r /(type|Id)=83$/s/size=[^,]+/size=7497728/
+  2017-05-30-raspbian-shrunk.img
sfdisk 2017-05-30-raspbian-shrunk.img
Checking that no-one is using this disk right now ... OK

Disk 2017-05-30-raspbian-shrunk.img: 3,7 GiB, 3909091328 bytes, 7634944 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x402e4a57

Old situation:

Device                          Boot Start     End Sectors Size Id Type
2017-05-30-raspbian-shrunk.img1       8192   92159   83968  41M  c W95 FAT32 (LBA)
2017-05-30-raspbian-shrunk.img2      92160 8369151 8276992   4G 83 Linux

>>> Script header accepted.
>>> Script header accepted.
>>> Script header accepted.
>>> Script header accepted.
>>> Created a new DOS disklabel with disk identifier 0x402e4a57.
2017-05-30-raspbian-shrunk.img1: Created a new partition 1 of type 'W95 FAT32 (LBA)' and of size 41 MiB.
Partition #1 contains a vfat signature.
2017-05-30-raspbian-shrunk.img2: Created a new partition 2 of type 'Linux' and of size 3,6 GiB.
Partition #2 contains a ext4 signature.
2017-05-30-raspbian-shrunk.img3: Done.

New situation:

Device                          Boot Start     End Sectors  Size Id Type
2017-05-30-raspbian-shrunk.img1       8192   92159   83968   41M  c W95 FAT32 (LBA)
2017-05-30-raspbian-shrunk.img2      92160 7589887 7497728  3,6G 83 Linux

The partition table has been altered.
Syncing disks.
+ partx 2017-05-30-raspbian-shrunk.img
NR START     END SECTORS SIZE NAME UUID
 1  8192   92159   83968  41M      402e4a57-01
 2 92160 7589887 7497728 3,6G      402e4a57-02
+ losetup -f
+ DEST_LOOP_DEV=/dev/loop2
+ losetup /dev/loop2 2017-05-30-raspbian-shrunk.img
+ partprobe /dev/loop2
+ mkfs.ext4 /dev/loop2p2
mke2fs 1.43.4 (31-Jan-2017)
/dev/loop2p2 contiene un file system ext4
	last mounted on /tmp/src.28253 on Tue May 30 18:34:42 2017
Proceed anyway? (y,N) y

+ /bin/true
+ mkdir /tmp/dest.28390
+ mount /dev/loop2p2 /tmp/dest.28390
mount: wrong fs type, bad option, bad superblock on /dev/loop2p2,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
```

And the base image should be the right one:

```
-rw-r--r-- 1 rm   rm   4285005824 mag 30 18:34 2017-04-10-raspbian-jessie.img
-rw-r--r-- 1 rm   rm   1297862656 mag 30 18:18 2017-04-10-raspbian-jessie-lite.img
```

**Comment by l1k** [comment]
Hm, the FAT partition has 41M again. :-( Should be 63M.
```
Old situation:

Device                          Boot Start     End Sectors Size Id Type
2017-05-30-raspbian-shrunk.img1       8192   92159   83968  41M  c W95 FAT32 (LBA)
2017-05-30-raspbian-shrunk.img2      92160 8369151 8276992   4G 83 Linux
```
Either you've once again tried to shrink the lite image, or the Foundation has silently replaced `2017-04-10-raspbian-jessie.img` with a version which has a smaller FAT partition. I'll double-check the latter, stand by.

**Comment by l1k** [comment]
Okay, it turns out that images up to 2017-03-02 used a 63M FAT partition and I wrote the script based on those older images. The Foundation reduced the FAT partition to 41M starting with 2017-04-10. I never noticed that because the version of mkfs.ext4 I use (1.42.12, 29-Aug-2014) does not seem to complain about an existing filesystem.

Please stand by while I work on a fix. Thanks a lot for bringing this to our attention.

**Comment by l1k** [comment]
This is addressed now by commit e7b0c61d87b7, could you test if it fixes the issue for you?

BTW the 41M FAT partition is present on both the lite and the non-lite image. It's not that the non-lite version uses a bigger FAT partition, so I was wrong above. Sorry for having alleged that you were invoking the script with the wrong image, you were totally innocent. :)

**Comment by xrmx** [comment]
No offense taken :) Verified it works for me too, thanks for fixing it!

**Comment by xrmx** [comment]
No offense taken :) Verified it works for me too, thanks for fixing it!
