### ISSUE TITLE
Buster is now oldstable

### ISSUE THREAD

**Issue by Darneas** [RevolutionPi/imagebakery#44]
The raspios_armhf-2021-03-25 is based on Debian buster, which is now "oldstable". apt-get update fails with:

"changed its 'Suite' from 'stable' to 'oldstable'"

This must be accepted explicitly and apt-secure is proposed.
I guess another way would be to update to 'oldstable' in the .list files.
I also found this online: sudo apt-get update --allow-releaseinfo-change

What would be the best way to change the customize_image.sh to accommodate for this?

**Comment by nbuchwitz** [comment]
@xrmx thanks for reporting this. With the recent buster images from the RPi Foundation this is not happening as it is already oldstable. Nevertheless we fixed the imagebakery in order to allow builds with older images.

**Comment by xrmx** [comment]
@nbuchwitz you are welcom! I'm not sure I'm the one to thank though :)

**Comment by nbuchwitz** [comment]
Sorry, wrong mention. I intented to answer @Darneas  :-)
