### ISSUE TITLE
customize_image.sh fails when trying to overwrite logrotate

### ISSUE THREAD

**Issue by DorEcoplant** [RevolutionPi/imagebakery#8]
When running customize_image.sh on Raspbian Stretch lite 08-04-2019 , getting an error : 
failed to create symbolic link '$IMAGEDIR/etc/cron.hourly/logrotate': File exists

Adding a line in the shell script to remove the $IMAGEDIR/etc/cron.hourly/logrotate solves the issue.

**Comment by l1k** [comment]
customize_image.sh is only intended to be run on a clean Raspbian image. However /etc/cron.hourly/logrotate does not exist on a clean Raspbian image. Most likely you've invoked customize_image.sh on an already customized image.

**Comment by DorEcoplant** [comment]
Oh man... Sorry for that. 
Thank you ! closing the issue
