### ISSUE TITLE
How to expand /dev/root size?

### ISSUE THREAD

**Issue by alextran1502** [RevolutionPi/imagebakery#9]
Hello,

I can build the image successfully, there is one part that I don't know how to make it work is either increasing the size of the available space for the application. I tried to comment out this part but still the image is around 1.6GB ~ 1.7GB

```bash
# shrink image to speed up flashing
resize2fs -M "$LOOPDEVICE"p2
PARTSIZE=$(dumpe2fs -h "$LOOPDEVICE"p2 | egrep "^Block count:" | cut -d" " -f3-)
PARTSIZE=$(($PARTSIZE * 16))   # ext4 uses 4k blocks, partitions use 512 bytes
sfdisk --dump "$LOOPDEVICE" | /bin/sed -r -e "\$!n
\$s/size=[^,]+/size=$PARTSIZE/" | /sbin/sfdisk "$LOOPDEVICE"
PARTSTART=$(cat /sys/block/$(basename "$LOOPDEVICE")/$(basename "$LOOPDEVICE"p2)/start)
truncate -s $((512 * ($PARTSTART + $PARTSIZE))) "$1"
```

Can you advise with some solutions? 

Thanks,

**Comment by iluminat23** [comment]
Sorry for the late response.

I'm not sure about what you are trying to accomplish. Have you problems installing packages in the **image** due to the size. Or do you want to resize the partition on the target, that it is as big as your storage?

Best regards
Philipp

**Comment by zhan-kunbus** [comment]
Hi, 

in /usr/sbin/revpi-factory-reset of deb package piserial you may find what you need.

_# resize root partition
dev=mmcblk0
total_size="$(/bin/cat /sys/block/$dev/size)"
last_part="$(cd /dev ; /bin/ls ${dev}p* | /usr/bin/tail -1)"
last_part_start="$(/bin/cat /sys/block/$dev/$last_part/start)"
last_part_size="$(/bin/cat /sys/block/$dev/$last_part/size)"
last_part_max="$(($total_size - $last_part_start))"
if [ "$last_part_size" -lt "$last_part_max" ] ; then
        /sbin/sfdisk -q --dump "/dev/$dev" | /bin/sed -r -e "\$!n
\$s/size=[^,]+/size=$last_part_max/" | /sbin/sfdisk -q -f --no-reread --no-tell-kernel "/dev/$dev"
        /sbin/partprobe "/dev/$dev"
        /sbin/resize2fs "/dev/$last_part"
fi_

**Comment by alextran1502** [comment]
Hi, I found a solution to my problem. So to reword it, when we finished building an image, it is "compressed" to flash to the board faster. To expand the size of the image to the rest of the partition, I just need to go into raspi-config and expand the disk. However, I wonder if we can do this on command line so I can create a first-boot script to do this automatically.

**Comment by zhan-kunbus** [comment]
Hi, not sure is the following the information you need.

fdisk, which is used by raspi-config -> Advance -> A1, is a dialog-driven program for creation and manipulation of partition tables.  --- from the man page of fdisk.
And sfdisk, which is used in the script in comment above, is a script-oriented tool for partitioning any block device. --- from the man page of sfdisk

**Comment by alextran1502** [comment]
I will look more into it. Thank you for the pointer.
